Avoid wrapping constants in multiple layers of InlineParam
intel/device-modeling-language pull request #214
Opened 2023-09-28 16:58 UTC by mandolaerik

This sometimes triggered errors in the old PCI library
(`update_mapping("I/O")`)

2023-09-28 17:26 UTC, syssimics commented
Verification [#12261822](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12261822): pass

2023-09-29 12:47 UTC, lwaern-intel reviewed
@mandolaerik Why no releasenote?

2023-10-12 09:17 UTC, lwaern-intel requested changes
Have a releasenote and this is an easy approve.

2023-10-30 13:52 UTC, lwaern-intel commented
@mandolaerik Updated with suggestion of releasenote. Give a thumbs-up and I'll merge myself.

2023-10-30 14:01 UTC, mandolaerik commented
me forgetting to merge this one is perhaps the reason why b454053d877a45fbd4bb1b6fef778a73e9a8a7ce was needed?

2023-10-30 14:45 UTC, lwaern-intel approved these changes

2023-10-30 14:46 UTC, merged