Improve some #line directives
intel/device-modeling-language pull request #223
Opened 2023-10-11 20:39 UTC by mandolaerik

2023-10-11 20:40 UTC, mandolaerik commented
Part of #220

2023-10-12 07:06 UTC, lwaern-intel commented on py/dml/c_backend.py
> +                    # Inline the init method
Get rid of this comment.

2023-10-12 07:07 UTC, lwaern-intel commented
This will be redundant with #221, but can be allowed as a stop-gap since #221 is rapidly expanding its complexity.

2023-10-12 08:26 UTC, syssimics commented
Verification [#12332186](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12332186): pass

2023-10-12 08:55 UTC, mandolaerik commented
[Test MCA L](https://teamcity01-ir.devtools.intel.com/viewQueued.html?itemId=12334000)

2023-10-12 09:14 UTC, lwaern-intel requested changes
get rid of it and this is an easy approve.

2023-10-12 12:55 UTC, mandolaerik commented on py/dml/c_backend.py
> +                    # Inline the init method
thanks, removed

2023-10-12 13:43 UTC, syssimics commented
Verification [#12335683](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12335683): pass

2023-10-12 15:06 UTC, lwaern-intel approved these changes

2023-10-12 15:07 UTC, merged