Store all permutations in a global shared array, so that one 32-bit index per register is sufficient.
intel/device-modeling-language pull request #239
Opened 2023-11-14 19:38 UTC by mandolaerik

- remove unused method
- Avoid re-calculating read/write field order
- Store field order as permutation indices instead of field references
- Store all permutations in a global shared array, so that one 32-bit index per register is sufficient.

2023-11-14 19:45 UTC, syssimics commented
Verification [#12507032](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12507032): fail

2023-11-14 19:59 UTC, mandolaerik commented
This is yet unpolished, and meant as a basis for discussions (but at least 1.4/lib/fields passes).
* does this approach make sense, or is it a dead end?
* The memoization of `_get_read_fields` adds some ugliness -- just look at `_cleanup_permutation_table_helper` -- we can consider skipping this and keep hash tables instead, doing an identity_t lookup every time. Probably somewhat slower in runtime, and may use more or less mem, but the diff should not be dramatic.

2023-11-14 20:51 UTC, syssimics commented
Verification [#12507039](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12507039): fail

2023-11-15 09:00 UTC, lwaern-intel requested changes
I think this approach is... though not _pretty_, it is fine when adjusted. My big peeve is `_permutation_table_helper()`, but that's fixable (see comment.)

The guarantee we offer that the implicit calls of independent startups happen before independent startup memoized was to offer a degree of control when startup memoizeds had dependencies, so it's not like we're operating outside their boundary of what they were intended for (_except_ `_permutation_table_helper()`, which, again, is fixable.)

2023-11-15 10:48 UTC, lwaern-intel commented
We have segfaults, by the way! This may or may not be due to the thing I complained about, regardless, you'll want to track them down.

2023-11-16 15:54 UTC, johanhogberg approved these changes
Great work!
We e-mailed a new performance test which we didn't have earlier.
When we started with granite rapids we saw that it took very long time to enable-probes and we got down the time from over a minute to about 10 seconds.

We think that your refactoring actually should be slightly faster, but lets find out first.

2023-11-24 22:28 UTC, mandolaerik commented
This PR does demonstrate an interesting memoization technique, but after #243 it is no longer needed.

2023-11-24 22:28 UTC, closed without merging