Resolved paths in generated C-file's sources list
intel/device-modeling-language pull request #245
Opened 2023-12-01 14:54 UTC by TSonono

I did not write any tests for this since I'm not familiar with the repo. I tested it by "manually at least". Let me know if I should change something

2023-12-01 16:32 UTC, MagnusIntel approved these changes

2023-12-04 07:23 UTC, TSonono commented on py/dml/c_backend.py
> +        '\n'.join([' *   ' + str(Path(f).resolve()) for f in source_files]),
Thanks for the suggestion, fixed

2023-12-04 08:48 UTC, lwaern-intel requested changes
As stated in R.C., the `dead_dml_methods` script should be changed to assert on that the path is absolute. Something like:
```python
def dml_sources(c_file: Path) -> set[Path]:
    '''Given a DMLC-generated C file, return the set of DML files that
    were used to generate it'''
    def paths():
        for p in dml_sources_from_body(c_file.read_text()):
            p = Path(p)
            assert p.is_absolute(), p
            yield p
    return {p for p in paths()}
```

You're welcome to shorten that. Building a set by leveraging `.add()` is OK, I just wrote a generator adjustor for principle's sake.

Also, to test that the change and assertion works, modify the import in `tests/1.4/misc/dead_methods.dml` to
`import "../misc/dead_methods_imported.dml";`, with a comment stating why the import's like that (test that DMLC resolves the path in the source lists).

2023-12-04 13:43 UTC, lwaern-intel requested changes

2023-12-04 13:43 UTC, lwaern-intel commented on py/dead_dml_methods.py
> +            p = Path(p)
Cleaner:
```python
        for p in map(Path, dml_sources_from_body(c_file.read_text())):
            assert p.is_absolute(), f'{p} is not an absolute path'
            yield p
```

(thanks Erik!)

2023-12-04 13:47 UTC, TSonono commented on py/dead_dml_methods.py
> +            p = Path(p)
Nice

2023-12-04 16:42 UTC, syssimics commented
Verification [#12619624](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12619624): pass

2023-12-05 01:35 UTC, lwaern-intel approved these changes
👍

2023-12-05 07:30 UTC, merged