Use project mini-python
intel/device-modeling-language pull request #257
Opened 2024-02-05 16:36 UTC by jhbaarnh

This is in preparation for moving Python to an addon package.

2024-02-05 21:05 UTC, syssimics commented
Verification [#12943968](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12943968): pass

2024-02-06 09:02 UTC, lwaern-intel commented
Hmm... this breaks the DML job because it works by _not_ leveraging a Simics repo, but by using prebuilt packages. In order for the DML job to work, we'd need to patch tests.py in order to leverage that package (and then @andreashedstrom-intel can update the DML job to ensure that package is available). @mandolaerik What should be the plan of action, here? Is there any way we can reformulate this patch such that the DML job can be updated to work without needing any future changes in the DMLC repo? (And ideally, in such a way that would allow the DML job to be updated to be functional immediately; however, it's OK if it needs to wait until the addon package becomes available.)

2024-02-06 09:15 UTC, mandolaerik requested changes

2024-02-06 09:15 UTC, mandolaerik commented on test/tests.py
> +mini_python = [join(simics_repo_root(), "bin", f"mini-python{batch_suffix()}")]
simics_repo_root is only available when running from the  base repo, and we want the test to be runnable from a normal project. So better to use `testparams.project_path` here. Also, we should check if this change gives a significant performance penalty on Windows; if so, we should consider adding something to t126 that makes it use mini-python.exe directly.

2024-02-06 10:09 UTC, lwaern-intel approved these changes
Oh hey that just made the DML job Just Work, huh. That's great.
Approval is pending verification (not that I see why it would fail.)

2024-02-06 10:10 UTC, lwaern-intel requested changes

2024-02-06 10:10 UTC, lwaern-intel commented on test/tests.py
> +mini_python = [join(project_path(), "bin", f"mini-python{batch_suffix()}")]
Actually, either use `testparams.project_path`, or update existing usages of  `testparams.project_path` to use `project_path`

2024-02-06 10:37 UTC, syssimics commented
Verification [#12947213](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12947213): pass

2024-02-06 11:30 UTC, lwaern-intel commented on test/tests.py
> +                    f"mini-python{batch_suffix()}")]
I missed the `{batch_suffix()}` part. I'll run a quick Test W just to be sure it works OK there.

2024-02-06 11:38 UTC, lwaern-intel commented on test/tests.py
> +                    f"mini-python{batch_suffix()}")]
... or so I say yet TC decided to rebuild Build W for no reason. bah.

2024-02-06 13:29 UTC, lwaern-intel commented on test/tests.py
> +                    f"mini-python{batch_suffix()}")]
[Here's the run](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12947896&buildTypeId=SimicsCiSimics_MonoTests_TestWFast). All failures are unrelated, and the t126 suite is no slower, so I'd deem this good.

2024-02-06 13:31 UTC, lwaern-intel approved these changes

2024-02-06 14:11 UTC, jhbaarnh commented
@mandolaerik I need your approval too, since you clicked "request changes".

2024-02-06 14:35 UTC, mandolaerik approved these changes

2024-02-06 14:35 UTC, merged